version: '2.0'

services:
  haproxy:
    build: ./haproxy
    ports:
      - "80:80"
    depends_on:
      - a
      - b 
  a:
    build: ./a
    expose:
      - "3000"
  b:
    build: ./b
    expose:
      - "3000"